apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-dep
spec:
  
  replicas: 2
  selector:
    matchLabels:
      env: prod
    matchExpressions:
      - { key: team, operator: In, values: [ team1, team2 ] }
      - { key: tier, operator: In, values: [ frontend,backend ] }
  template:
    metadata:
      name: "webpod4"
      labels:
        env: prod
        team: team1
        tier: frontend

    spec:
      containers:
      - name: "webc1"
        image: dockerhandson/java-web-app:2
        ports:
          - containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-svc-dep
spec:
  type: NodePort
  selector:
    env: prod
  ports:
  - port: 80
    targetPort: 8080
